using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BaseCards : MonoBehaviour {

    [SerializeField] GameController gameController;

    public void AddCardsToDeck() {

        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Like Mike", "You and an opponent of your choice both jump as high as you can.  The other players vote who loses and they shall drink 5.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "The Slap", "You and an opponent of your choice take turns slapping each others hands, first person to say Uncle needs to sip a few.  Let's say 3.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Twerky", "The crowd chooses someone for you to twerk off with, winner passes out 5 drinks for their ass skills");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Drop it like Snoop", "You and an opponent of your choice have a rap battle. Pick a 3rd player to beatbox. Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Air Hendricks", "Have an Air Guitar battle with another player of your choice.  Whoever is voted the loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Dance Off", "Have a dance battle with another player of your choice.  Crowd voted loser drinks!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Bottoms Up", "You and someone else have a chug contest.  Loser, well, drinks more.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Push it Up", "Pick an opponent to go push up for push up with.  Loser knows what to do.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Rock Paper Scissors", "Pick an opponent and go for the best of 3.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Rock Paper Lasers", "Pick an opponent and play rock paper scissors, but you can't use Rock, Paper or Scissors.  Debate why your new weapon won.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Staring Contest", "Loser Drinks.  If you don't know what you are supposed to do here, finish your drink");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Oh Say Can you See", "Sing the National Anthem with someone else.  Alternate lines.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Over the Top", "Choose someone to arm wrestle with.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Keeping it Gassy", "Loudest burp wins.  Second place drinks more fuel.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "1..2..3..4..", "You just declared a thumb war on someone.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "To Infinity and Beyond?", "Choose an opponent and go back and forth naming characters from movies about toys.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "PEN15", "Pick someone to have a screaming contest with using only the word Penis.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Yodels without Chocolate", "Have a yodeling contest with someone.  Crowd picks the winner, loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Gobble Gobble", "Have a turkey gobbling contest with someone.  Crowd picks the winner, loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "King of the Jungle", "Pick an animal sound and an opponent.  Whoever makes that sound best according to the crowd wins, loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Car Sound", "Pick any car sound and an opponent.  Whoever makes that sound best according to the crowd wins, loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Doin it like Donkey Kong", "Pick an opponent and an animal.  Whoever impersonates that animal the best according to the crowd wins, loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Yo mama so...", "Pick an opponent and come up with your best attempt to finish that line. The best one according to the other peons in the room wins, loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Insult-a-Thon", "Pick an opponent to verbally beat the sh*t out of.  Continue until someone taps out.  They finish their drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "The Lady Pleaser", "Compare tongues with someone else to see who has a longer one.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Your dick is so small...", "Pick someone to duel it out finishing that line.  Winner laughs as the loser drinks.  Seriously, you have to laugh or you drink too.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Bruce Buffer", "Pick your opponent, and become an announcer for a topic of your choice.  Whoever does a better job according to the crowd wins and hands out 3 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Don't Breathe", "Breath holding contest!  Choose someone to compete against.  Hold it as long as you can, because loser downs their drink");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Head to Head", 1, "Get to the Choppa", "Arnold Contest.  Choose someone in the room to compete against with Arnold impressions, and we do not mean through voice.  Flex it instead, let's see what you got.");

        // Action
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Playground Antics", "Make up a new name for someone.  That's now their name.  Anytime someone addresses them incorrectly, they drink.  This is not an inconvenience, this is for the rest of the game.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "CHUG! CHUG! CHUG!", "Finish your drink.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Drive like an Egyptian", "Reverse the direction of play.  Cheers someone who now has to have a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "CHUG YOU BASTARD", "Pick someone who now has to finish their drink.  Everyone should stare while they do so.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Karaoke Time", "Sing us a song, you're the piano man!!  No, seriously.  Sing for 30 seconds then have a drink.  Anyone who joins in gets to make one of the silent people drink as well.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Balls to You", "Rhyme with Balls.  Go around the room.  Whoever can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Friend in Need", "Someone looks like they really need a drink.  Accommodate them.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "What's in a name?", "State the person to your rights middle name.  Continue around the room until someone can't do it, then they drink.  If it comes back to you, finish your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Who has 2 thumbs and...", "Put your thumb on a surface and just wait for everyone else to catch on.  The oblivious idiot who is last drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Eyes Wide Shut", "Staring contest!  Pick someone and go to work.  First one to blink has a drink and henceforth must be referred to as Nemo.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Twerk it for me", "Show everyone what your mama gave you by twerking to no music.  Or finish your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "King of the Jungle", "Make an African animal sound.  The first person to guess it can pass out 3 drinks, only after repeating the sound.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Heads or Tails?", "Flip anything with 2 sides.  Call it mid air.  If you are right, pick someone to drink.  Otherwise, have one yourself.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Sorry", "No reason at all besides you are a self centered low life individual who deserves this, drink for 5 seconds (let your friends count it out)");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Drop and Gimme 5", "Drop and do 5 pushups.  If you do, pick 3 associates to drink.  Otherwise have a drink yourself and join a gym.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Triple Play", "The next 3 turns are yours.  Let's get started with a drink.  Enjoy!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Cousin Eddie's Favorite", "Play guess the number with someone, you pick the number.  WHEN they get it wrong, they drink.  If they get it right, finish your drink because you've missed the point entirely.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Come on shake your booty", "Form a conga line.  Loop around the table or counter or wherever you are.  Everyone drinks this time.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Never have I ever...", "Play the game.  Anybody who has done your thing drinks.  If you don't know how to play, finish your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Ya Better Know", "Sing the National Anthem to its completion by yourself without any help.  If you're a patriot and could sing it pass out 10 drinks.  Slam your drink if you couldn't you unpatriotic prick");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Pucker up Buttercup", "Kiss the person to your left or finish your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "It's called fashion, look it up.", "Go around naming clothing/apparel companies.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The liquor's gunna let ME down?!", "Go around naming liquor brands.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Rhyme Time", "Pick a word, any word.  The person to your right must come up with a new word that rhymes.  Continue around till someone can't.  They drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Once Upon a Midnight Dreary", "Recite any verse from The Raven by Poe.  If you can do it, pick 2 other people to have a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "And the story goes...", "Once upon a time.... Go around, each person adding 1 word to that story.  First one to not make sense loses and drinks.  5 seconds max.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Ending Story", "So I says to Mabel, I says... Go around, each person adding a sentence to the story.  First one to not make sense loses and drinks.  5 Seconds max.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "New York Shore", "Name state capitals until someone can't.  They drink.  If they got zero right as in first round and they couldn't even name one, finish that drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The States Game", "Name a state.  The next person has to name the capital.  Go around repeating this pattern until someone is stuck and must drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Brrr-Exit", "Go around naming countries in Europe.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "General Tso Says So", "Go around naming countries in Asia.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Catch a Wave", "Go around naming countries in North America.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Oils Well", "Go around naming countries in Africa.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Great day to drink, eh?", "Go around naming provinces in Canada.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "USA! USA!", "Go around naming USA Presidents.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Watch the drip", "Go around naming luxury clothing brands.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Foreigner", "Go around naming foreign car brands.  Loser drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Pocket Change", "How much did 'The Wall' cost Mexico?  No wrong answers here.  Anyone still breathing after the argument take a drink!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Storytelling", "Start with a word.  Go around the room, each person has to recite the story so far and add 1 additional word.  First person to mess it up drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Ludicrous Speed", "Last person to the fridge has to finish their drink.  GO!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "I Like the Taste", "Reasons to drink.  Go around until someone runs out of ideas.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Rick Rolled", "Name things Rick Astley would never do.  Go around until someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Chuck Norris", "Name things Chuck Norris would never do.  Go around until someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Every Step You Take", "Name an 80s Song.  Keep going till someone messes up and takes a drink for their lack of knowledge.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Nerdvana", "Name a 90s song.  Keep going till someone messes up and takes a drink for their lack of knowledge.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Call up the Ludes Dude", "Name a 70s song.  Keep going till someone messes up and takes a drink for their lack of knowledge.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Millennial Greatness", "Name a 2010s song.  Keep going till someone messes up and takes a drink for their lack of knowledge.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Y2K", "Name a 2000s song.  Keep going till someone messes up and takes a drink for their lack of knowledge.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Stones'd", "Name a Rolling Stones song and then keep it going until someone can't get no satisfaction.  Then they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Help!", "Go around naming Beatles songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Lady Gagagagagagagaga", "Go around naming Lady Gaga songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Tekashi", "Go around naming 6ix9ine songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Play it Again", "Go around naming Luke Bryan songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "God's Country", "Go around naming Blake Shelton songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Black", "Go around naming Metallica songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "OVO", "Go around naming Drake songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "First Date", "Go around naming Blink-182 songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Cole World", "Go around naming J. Cole songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "RIP Juice", "Go around naming Juice WRLD songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Luv Is..", "Go around naming Lil Uzi Vert songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Kush & OJ", "Go around naming Wiz Kahlifa songs.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "It's Weezy baby!", "Go around naming Lil Wayne albums or mixtapes.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Making a Left Turn with Style", "Name a NASCAR driver, past or present.  First one to fail in doing so drinks in honor of The Intimidator");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "@!#$)*%! SPORTS", "Name a sport.  Go around the room, each person naming any sport.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Don't #!@& With Cats!", "Go around naming professional sports teams with cats as their mascot.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Birds of a feather", "Go around naming professional sports teams with birds as their mascot.  Loser drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Classing it up", "Fast Food on Easter Sunday!  Name fast food restaurants, first person to fail or repeat drinks.  This should not be hard. Uhuhuhuhuh hard.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Little Bell Caesars", "Taco Bell or Little Caesars? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "McBurger King", "McDonald's or Burger King? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "All Pizza is not Equal", "New York or Chicago style pizza?  Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Go-Gurt", "Make up yogurt flavors.  They can't be real, but must be technically edible.  When someone is stumped or fails, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an A", "Go around the room naming movies that start with the letter A.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with a B", "Go around the room naming movies that start with the letter B.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with a C", "Go around the room naming movies that start with the letter C.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with a D", "Go around the room naming movies that start with the letter D.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an E", "Go around the room naming movies that start with the letter E.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an F", "Go around the room naming movies that start with the letter F.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with a G", "Go around the room naming movies that start with the letter G.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an H", "Go around the room naming movies that start with the letter H.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an L", "Go around the room naming movies that start with the letter L.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an M", "Go around the room naming movies that start with the letter M.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an N", "Go around the room naming movies that start with the letter N.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with a P", "Go around the room naming movies that start with the letter P.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an R", "Go around the room naming movies that start with the letter R.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with an S", "Go around the room naming movies that start with the letter S.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Movies with a T", "Go around the room naming movies that start with the letter T.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an A", "Go around the room naming TV Shows that start with the letter A.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with a B", "Go around the room naming TV Shows that start with the letter B.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with a C", "Go around the room naming TV Shows that start with the letter C.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with a D", "Go around the room naming TV Shows that start with the letter D.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an E", "Go around the room naming TV Shows that start with the letter E.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an F", "Go around the room naming TV Shows that start with the letter F.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with a G", "Go around the room naming TV Shows that start with the letter G.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an H", "Go around the room naming TV Shows that start with the letter H.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an L", "Go around the room naming TV Shows that start with the letter L.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an M", "Go around the room naming TV Shows that start with the letter M.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an N", "Go around the room naming TV Shows that start with the letter N.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with a P", "Go around the room naming TV Shows that start with the letter P.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an R", "Go around the room naming TV Shows that start with the letter R.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with an S", "Go around the room naming TV Shows that start with the letter S.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "TV Shows with a T", "Go around the room naming TV Shows that start with the letter T.  When someone can't, they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Trekkin", "Name a Star Trek character.  Go around the room until someone can't, and they have to drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Thursday Night Live", "Name sketches from SNL.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "SNL Celebs", "Name cast members from SNL.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Seinfeld Celebs", "Name cast members from Seinfeld.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Friends Celebs", "Name cast members from Friends.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "True Blood", "Name cast members from True Blood.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Twilight", "Name cast members from Twilight.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Westworld", "Name cast members from Westworld.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Breaking Bad Celebs", "Name cast members from Breaking Bad.  First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Yippie Kiyay Mister Falcon", "Go around the room quoting the movie.  Whoever can't drinks.  Whoever doesn't know what movie we are referring to, finish your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Obscure References", "Quote a line from a movie.  Everyone has to do a different quote from that movie without naming it until someone can't.  Then they drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "F'ing Snow White", "Go around the room naming fairy tale characters until someone can't.  They drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "DUDE IT'S YOUR SISTER", "Go around the room naming Star Wars characters.  The force is not strong with the first person who can't. They drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Come at me bro", "Go around the room naming action movies.  First person unable to do so drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Burt", "Name Burt Reynolds movies.  Whoever gets stuck must hang their head in shame and drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Order is Everything", "Rank the Star Wars movies.  The crowd is your guide.  If you mess up the order or put anything except Empire as #1, drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "I'M CONFUSED", "Go around the room naming Nicholas Cage 'movies' until someone can't.  They Drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Kung Foo King", "Name Jackie Chan movies.  Whoever gets stuck must perform a karate kick and drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "2 Fast 4 Y'all", "Name Fast and Furious movies.  Whoever gets stuck must finish their drink for Paul.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Super Wario", "Name a Video Game character.  Keep going till someone can't name one.  They drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Risk(y Business)", "Name a territory in Risk.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Nerdvana", "Name a video game.  Go around, first one to hit a wall has a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Duty Calls", "Name COD games in order, first person to name one out of order gets sent to the gulag for a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Seinfeld Who?", "Go around the room doing quotes from Seinfeld.  Whoever can't pull it off takes a drink baby!!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Mazeltov", "Name the character who Cartman always rips on for his religious beliefs in South Park.  If you can't do it, hang your head in shame and leave it that way.  And take a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Trailer Park Who?", "Go around the room doing Trailer Park Boys quotes. If you can't, take a drinky poo Rand.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Rickyisms", "Go around the room reciting Rickyisms from Trailer Park Boys. First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Lion King", "Go around the room listing Lion King characters. First person who can't drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Did she do it ?", "Did Carole Baskin feed her husband to the tigers? Take a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Tiger King", "Will Joe Exotic ever get out of prison early? Take a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Scooby Dooby Dooooo", "Go around the room and do your best Scooby-Doo impression, then take a vote on who was the best.  They get to hand out 2 Scooby-Snack-Drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "Meter Stick", "Who's the shortest in the room?  Alright shorty, take a drink!!!", "Revenge!  Now hand out drinks to all of the tall people.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Dancing Sucks", "Go around the room naming Wedding songs you can dance to.  Ahh ya can't?  Then have a drink with your two left feet.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Red Rocks", "If you haven't been to a concert in the last year drink to your own lame-ness.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Think you're tough", "Vote for who can do the most push-ups. Whoever wins the vote has to have a nice long drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "You Don't Say...", "Who is the biggest dumbass in the room?  Everyone vote!  That person has to have a drink.  Tap again for additional instructions.", "OK Dumbass!  Now hand out 3 drinks to your haters.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "Street Smartz", "Vote for the smartest person in the room, then tap for additional instructions.", "Everyone except the winner of the vote drinks.  What did you think was gonna happen?");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "That F'ing Owl Took My lollipop", "How many licks does it take to get to the center of a tootsie pop? Everyone guess, then tap for additional instructions.", "There isn't an answer haven't you seen the commercials?!  Everybody drinks!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Not Quite Pebbles", "Go around the room naming types of fruit.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Naughty Foreplay Lingo", "Go around the room naming NFL teams.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Major League Bruhs", "Go around the room naming MLB teams. First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Mighty Light Sabers", "Go around the room naming MLS teams. First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Nerf HS-3000 Lasers", "Go around the room naming NHL teams. First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Just say Tiger Woods", "Go around the room naming professional Golfers. First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Sam Adams Says...", "Go around the room naming beer breweries. First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Swimmin' upstream", "Go around the room naming types of fish.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Butterscotch Cowboy Says What?", "Go around the room naming Owen Wilson movies.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "What ever happened to DJ Jazzy Jeff??", "Go around the room naming Will Smith movies.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Unlike this game, your heart might go on", "Go around the room naming Leonardo DeCaprio movies.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Close eyes, point, win", "Go around the room naming Tom Hanks movies.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Jimmy you know I didn't see that", "Go around the room naming Samuel L. Jackson movies.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Caribbean Pirate", "Go around the room naming Johnny Depp movies.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "What's that Smell?", "Around the room, who has farted within the last 10 minutes?  Own up to it and take a quick swig");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "We've All Done it....", "If you've texted your ex recently, take a drink.  Have some self restraint.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Who washes clothes every day anyway", "If you've taken the ‘walk of shame' recently, take a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "That stinks", "If you've ever shat yourself in public, take a drink. And feel free to share the story.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "Good for the goose...", "Vote on who you think has slept with the most people, then tap again.", "The person voted to have the highest score hands out 3 drinks!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Loafin Around", "Around the room name types of bread.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "You Can't Do That", "Go around the room naming Nickelodeon shows.  First person who can't drinks.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Gooseegg", "Five teams in NFL history have gone 0 - 16.  Name one.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Ol Switcheroo", "Switch places with anyone.  Then both have a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "What's in a bill", "You are a platypus for the next 30 seconds.  If you can make people laugh they have to drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Bottoms Up...not in a good way", "Whoever has puked from drinking recently, have a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "I just had seeexxxx!", "Anyone who has had a one night stand recently, nice win.  Finish your drink to celebrate it.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "This space intentionally left black", "Anyone who has blacked out recently, drink up you party animal!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "We are the Champions!", "Start a singalong.  Anyone who can't or doesnt know the words has to drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "B-Ball", "Jordan or Lebron?  Put it to a vote.  Losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Uncle Joey", "Everyone point to the person they believe would be able to lie their way out of going to jail.  The winner has a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Hell with This", "You're in hell and there's a very slim chance to escape.  Who would you want with you?  That dirty bastard gets to slam their drink with you.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Pump....You Up", "My Austrian friend says they can lift a ton of weight.  Who in the room do you believe is the most Arnold?  The strongest in the room has a large gulp of that liquid protein");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Nick at Night?", "Go around the room naming Nickelodeon shows.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "Bigger is Better", "Who's the largest Bitch in the room?  Come on, you know what I mean. Point out the person that is the most self centered ass in the room so they can drink.", "Now who is literally the largest bitch in the room.  You get to drink too, mainly because we know you can hold your own.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Nobody should get this right", "Think of a number, now go around the room counterclockwise asking folks to guess it.  Every incorrect guesser gets a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Rule 1: Cardio.", "Zombie Pandemic time!!!  Around the room choose a weapon that you would not be without in the apocalypse. Whoever has the best idea by vote gets to pass out 3 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Woof Woof Woof Woof", "Who knew that the dogs vs cats question would come up.  If you own a cat go ahead and take a drink.  Dogs are way cooler.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Meowschwitz", "If you own a dog, take a drink.  We all know cats are way smarter.  My cat tells me that all the time.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Old Geezer", "Choose the oldest person in the room.  They are enlisted into your punishment of sharing 2 drinks.  If you are the oldest then double down and share 4 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Happy Birthday to you", "Congratulations on yet another year!  Down your drink while everyone sings happy birthday to you.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Is there anyone out there?", "Tell everyone in the room a time where you have literally almost pissed yourself you were so scared.  Then pass out 3 drinks. If you can't due to your hardass stature take a drink yourself John McClane");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Whoop, there it is!", "Point out who has the largest mole in the room and make that person drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "Party like it's 1999", "Pick someone in the room and enjoy getting force feeding them their drink. Yeah that's right you grab their beer and feed it to em.", "Karma's a b*tch!  Whoever just got force fed their drink now gets to do it back to the person that did it to them.  Be sure to spill a little.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Love is on the way", "It may be love that you're feeling, but you are not going to like who it is with.  Enjoy making out with your drink before you slam it back.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Bottle Time!", "Let's get a bottle out (yeah I am sure you are all drinking cans).  Find one in your recycling bin or use the damn can.  Spin it on any surface, that person has to finish their beverage.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Dude There's a Beverage Here!", "Go around the room naming mixed drinks you can order at the bar containing tequila. First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Absolut-ely", "Go around the room naming mixed drinks you can order at the bar containing vodka.  First person who can't drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "So this one time the pool was closed....", "Go around the room telling the craziest thing you've ever done while hammered.  Everybody takes a drink for each story shared. If someone has a lame story the crowd can vote to make them finish their beverage.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Bare Essentials", "Which would you give up first, underwear or socks? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Tool Time", "Around the room start naming tools used for working on vehicles, this should be entertaining.  If you can't name one have two sips.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Left or Right handed", "Are you right or left handed?  Around the room whoever is the same as you is safe.  The others need to drink five.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Do you even Lift Bro", "Can you bench over 135 lbs?  Let the room take a vote and if you win you pass out two drinks, but if you lose you skull your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Witchcraft", "How many of you in the room have used a ouija board in your life?  For the number of hands up you weirdos get to partake in that many sips.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Where they at thoooo", "Choose the person in the room that has flaked on plans they had most recently.  Then slap em with five sips!!!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "SuperSize Me", "Take a vote.  Do you supersize those meals from Mcdees??  If you don’t go ahead and take a drink because bigger is better.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Burnt Out", "Who here has had a home appliance burn out from your a$$ overusing it?  If you have go ahead and take one drink for mourning");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "You Handy or Nah", "Are you a handyman/handywoman?  Have the room put it to a vote and if it's a yes then you pass out 5.  If it is a no then you can drink 3 for your lack of abilities");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Roses and Balls", "Roses are red, violets are blue, whose balls are the most blue?  Everyone get in on this sh*t and the loser drinks for not putting out - The whole drink!!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Name That Beer", "Around the room name brands of beer.  Did you really run out?  Slam your damn drink");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Color B", "Go around the room naming a color that starts with the letter B.  If you can't then your a B so drink three");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Who would do that", "Tell the group your nastiest, nastiest story and whoever gives reaction to it takes a sip.  If it wasn't nasty enough you drink 10!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Don't Blame Me", "Point out the person in the room that never owns up to anything.  Now that selfish bastard has to own up to drinking 5!!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Home?", "Do you own a house? If so, good for you, drink 3 for that mortgage payment.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Broke A$$", "Who here in the room has under $1,000 in their bank account? Now have a drink to soak in your feelings.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "You Nasty", "Around the room if you have gotten shit on your hands recently then take five drinks you nasty bastard.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "How Low Can Ya Go", "Everyone drop it like it's hot and get as low as you can.  Whoever got the lowest gets to pass out 4 drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Slick", "Who in the room do you think gets away with the most sh*t?  They are just a terrible person and now have to take a drink");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Incoherence", "Name the person in the room that you believe has the worst penmanship.  That illiterate prick gets to have a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Giraffe", "Choose the person with the longest neck in the room and tell them to drink to fill that jugular.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "That's My Drink", "Grab the person to your left's drink and take a swig, We do not care if you like it or not", "And now to the right, grab that person's drink to the right of you and snag a swig");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "M-I-C...K-E-Y...", "Go around the room naming Disney characters.  Whoever gets stumped has a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "I don't wanna go", "Go around the room coming up with excuses why you couldn't go to work.  Whoever runs outta gas or the crowd determines has a lame answer drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "I'd Love to but...", "Around the room we go coming up with excuses why you can't go on that date.  Lame answer loses and drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Oh look at the time", "You show up for a date and they do NOT look like their profile pic.  How are you getting out?  Worst answer by majority vote drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Hit and Run", "So you \"got lucky\", and don't feel like staying the night.  What excuse are you using?  Lamest answer by majority vote drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Ghosting", "You just ran into someone you ghosted at the bar.  What's your excuse scumbag?  Around the room worst answer drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Impersonation Time", "Pick a person to impersonate.  Pick anyone.  Whoever guesses right hands out 2 drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Like a Rock", "Impersonate an inanimate object.  Anything. Seriously anything.  Whoever guesses hands out 2 drinks.  If nobody guesses, your untalented ass takes a 5 second drink that your friends count out.  As slow as they want.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Smoke or Drink", "Which would you give up first, A little toking or a little drinking? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Coffee Fanatic", "Choose the person in the room you believe drinks the most coffee.  Hand two drinks to their energetic ass");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Where the Wild Things Are", " All you 90s babies drink 2 for being the coolest");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Big Hair Time", "All you 80s babies drink 2 for introducing the world to what big hair meant");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Dumbest laugh", "Who in the room who has the dumbest laugh?  Yeah that's right, call ‘em out on it.  They drink one for their annoying giggles.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Most Traveled", "Who in the room is known as the traveler?  Make them drink three for their so called amazing trips");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Who is Hood", "Around the room come up with the most thug phrase you can think of.  The winner gets to pass out 3 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather only be able to sh*t in public restrooms or only be able to sh*t with somebody watching? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Sh!tz", "Tell everyone a time you had to go so bad you couldn't hold it, then enjoy a nice long pull for your embarrassment");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Damn Dating Apps", "Who in the room has ever sat there late at night swiping right over and over again?  Go ahead and drink in your filth.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Bazinga", "You choose who in the room is the most socially awkward and give them 3 drinks to loosen ‘em up a little.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Carrot Debacle", "Put it to a vote, carrots raw or cooked? Losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Up Down", "Who in the room believes fishing is relaxing?  Send 2 drinks down these happy go lucky folks throats");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Batman", "Let everyone hear your best Batman voice.  If you nailed it, pass out two drinks.  If you sounded like a penguin take two drinks yourself.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Raunchy", "Around the room choose, ranch on pizza or not?  Losers take a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather...", "Would you rather take a dump in the stall next to your boss or use a port-a-potty at a construction site in 100 degrees?  Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Which do you Prefer", "Vanilla or Chocolate?  Put the age old question to a vote and reward the winners with two drinks (you're crazy if it is not chocolate)");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "White Trash", "Who in the room seems to have the most white trash appearance?  Put it to a vote, the Hillbilly needs to drink 3.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather give up your phone or your drivers license? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather give up binge watching or social media? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather shout or sneeze every time you fart? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather only be able to whisper to people or only be able to shout?  Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather only be able to tip-toe or stomp when you walk? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather give up your favorite food or your favorite hobby? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Would you rather..", "Would you rather spend 10 minutes in a room full of spiders or snakes? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Do you know who my Dad is?!", "Who in the room is/was the most spoiled growing up?  Have them finish their drink.  Daddy's not going to bail you out of this one.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Why's my text green?", "Apple or Android? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Say What?", "Do you say it 'Tomato' or 'Tomato'?  Who cares, take a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "12th Man", "Who is the biggest sports fan in the room?  Send them a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "What's up my nerd?", "Who's the biggest nerd in the room?  Send them a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Tech Support", "Who's the most tech savvy person in the room?  Send them a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Donkey and the Elephant", "Which party is the right choice, Democrat or Republican?  Put it to a vote, losers drink.  Try not to kill anybody.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Pass the sticks", "Xbox or PlayStation? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Big 3", "Who makes the best cars? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "See the difference?", "Does all water taste the same? Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Sweet home Alabama", "Who in the room is the most country?  Send them a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Apocalyptica", "You get to choose one person in the room to help you get through a zombie apocalypse.  Both of you take a drink for your camaraderie.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 3, "To Be or Not To Be", "Alright Shakespeare, let's hear your best Romeo or Juliet Impression.  Then click for more Instructions", "If you could do an impression, drink 3 for being a damn nerd.  If not pass out 3 to those nerds who probably could");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "LLC", "Who in the room runs their own company?  Drink up to you damn over achievers!");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Heaven's Gates", "Choose someone in the room you know would get turned around at the Pearly Gates. Have them drink 2 for their future peril.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Is Church Fun?", "Around the room who do you think goes to church the most?  The chosen one passes out Seven Heavenly drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Snowball", "Who in the room do you believe is the biggest softy and easily has their feelings hurt?  Give ‘em three drinks and leave ‘em crying");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Pterodactyl", "Around the room, take turns impersonating the ol' flying dinosaur.  Best impersonation hands out two drinks");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "CO2 Beverages", "Coke or Pepsi? Put it to a vote and the loser drinks.  But seriously, everyone knows Coke owns the title");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Cigs Inside", "Anyone in the room Smoke?  If you do and you choose to do it inside, have five drinks.  Nasty Prick");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Get in there", "We dare you to sniff the person's rear to the left of you. If you refuse, take a drink as a penalty. But if you get all up in there hand out 2 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Zoom Zoom", "Have any of you had a zoom meeting in the past week?  Go ahead and have a nice long sip because we know how it is to deal with the bullsh*t");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Vroom Vroom", "Around the room let's hear those car impressions.  Worst takes a drink for probably driving a damn prius.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Steel Reserve", "Who here has had a sip of the good ol' malt liquor in the past month?  If you have we are honored to have you playing!  Hand out 4 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Laugh it up", "Go ahead and give yourself a nice slap in the mouth, then drink.  Reasoning?  Just enjoy it you sick bastard.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Get a Job", "Anybody in the room still living with your parents take a drink.  You'll move out someday.  Maybe.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "For the Brand", "Nike or Adidas?  Put it to a vote, losers drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Extra Parts", "Choose the person in the room that always skips reading the instructions.  Have them take a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "HS Royalty", "If prom was tonight, who in the room would be the prom king and/or queen?  Put it to a vote, those 2 drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "College or not", "This one could get interesting.  Those of you without degrees have a sip of wisdom from someone's drink that does have a degree.  Maybe all that debt was worth it after all.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Charades", "Get a charades idea from the person on your left in secret.  You have 30 seconds to get someone to guess it or you have to drink.  If the crowd decides it was too easy, you both have to drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Charades", "Get a charades idea from the person on your right in secret.  You have 30 seconds to get someone to guess it or you have to drink.  If the crowd decides it was too easy, you both have to drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Reverse-Charades", "Give a random person a charades idea in secret.  They have 30 seconds to get someone to guess correctly or you both drink.  If the crowd decides it was too easy, you both have to drink anyway.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "...of the Jungle", "Make an animal sound.  Whoever guesses it correctly hands out 2 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Sounding It Out", "Make a sound, anything you want.  Whoever guesses it correctly hands out 2 drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "You've got the biggest....", "Go ahead, finish that sentence while addressing the person on your left.  Or finish your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "You've got the biggest....", "Go ahead, finish that sentence while addressing the person on your right.  Or finish your drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "If I could, I would....", "Finish that sentence while addressing the person on your left.  If they agree with you, hand out 2 drinks.  If they do not, drink them yourself.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "If I could, I would....", "Finish that sentence while addressing the person on your right.  If they agree with you, hand out 2 drinks.  If they do not, drink them yourself.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "If I could go anywhere right now...", "Start it off and then go around the room.  Whoever has the best idea by popular opinion watches while everyone else has a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Celebrity Impersonation", "You have 30 seconds to impersonate a celebrity of your choice.  If someone guesses it, you each hand out a drink.  If not, you have a drink.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Song Sung You", "Name a hit song and go around the room.  First person to be unable to do so drinks.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Twin Cannons", "Grab a second drink.  Double fist till one of them is dry.  Start with a sip now.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Twin Cannons", "Grab a second drink.  Double fist till one of them is dry.  Start with a sip now.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Twin Cannons", "Grab a second drink.  Double fist till one of them is dry.  Start with a sip now.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Twin Cannons", "Grab a second drink.  Double fist till one of them is dry.  Start with a sip now.");
        gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Moose", "Ever seen a dog slurp their drink out of a bowl?  Get to it, grab a bowl, and everyone pour a little of their drink in and you suck it all up to the last drop. Yummmm!!");

        // Quarantine
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Lockdown", "Who in the room had the longest stay at home streak during the COVID - 19 Pandemic? Whoever stayed at home the longest passes out 3 drinks.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Kinky", "Around the room what is the most unique place you have done ‘it’ during quarantine?  Least interesting location have a drink.  If you haven’t gotten any finish your drink.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "Couch Potato", "Who playing has been the laziest during quarantine and really let themselves go?  They get the honor of having a drink.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Action", 1, "The Covid P90", "Who's been the hardest worker during the COVID quarantine, hitting that home gym or doing DIY projects?  They hand out 2 drinks.");
               
        // Pioneer 8 Specials (beta only)
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Pioneer", 1, "The Jaime Clause", "If your drink is less than half full, finish it and get a fresh one.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Pioneer", 1, "The Rodney Clause", "Talk loudly.  Call people bastards.  Try to spill your drink a bit.  Oh yeah, and have a drink.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Pioneer", 1, "Seans-giving", "Leave the game early.  You're done drinking for 1 round");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Pioneer", 1, "Do you feel violaTED?", "Pack a bowl or finish your drink");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Pioneer", 1, "Swinging Smartt", "Name parts that make up a swing set.  Loser drinks.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Pioneer", 1, "Sam Style", "Grab a second drink.  You're now double fisting for the rest of the game.  Take a drink each time from each.");
        //gameController.AddCardToDeck(CardsManager.deckOfCards, "Pioneer", 1, "Jen-in-Place", "Jog in place for the rest of the game.");

    }
}