using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InconvenienceCards : MonoBehaviour {

    [SerializeField] GameController gameController;

    public void AddCardsToDeck() {

        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Bob Dole Doesn't Do That", "Begin referring to yourself only in the 3rd person.  If you get caught slipping, take a drink.", "You can stop referring to yourself in the 3rd person.  Arrogant b*tch.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Look Away", "Nobody can look at you until the inconvenience is lifted or they have to drink.", "Fantastic, we all get to look at your ugly ass again.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Put {name} in the bathroom", "You must face away from the group and stay that way.", "To everyone's dismay, You may now face the group again.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Duh", "Finish everything you say with 'duh'.", "Well look at that, you can speak coherently again.  Duh.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "I got you bro", "Put a hand on the person to your left's shoulder.  There it will stay. every time it comes off, you both have a drink.", "You can now take your hand off their shoulder you creep.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "The Ole Switcharoo", "Swap names with another player of your choice.  Both drink to your new names.  Anyone calling you the wrong name drinks", "You both can go back to being your boring ass selves.  It was fun though, wasn’t it?", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "No Moos is Good Moos", "Call someone a cow.  They can only moo from now on.  When you get home it might be a different story though, so choose wisely.", "Moo-velous.  You can stop with the cow sh*t now.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Accent Time", "The group chooses the accent you get to speak in until told otherwise.  Mess up, it'll cost ya a drink.", "You can stop with the accent nonsense.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Little green man", "There is now a little green man sitting on the rim of your drink.  You must remove him before you drink and put him back when you are finished.  If you get caught messing up, take a drink.", "Holy sh*t, did you drink him?!  Your little green man is gone!", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "You don't know me cuz!", "You're not allowed to call anybody by their name.  Drink when you mess up.", "You can go back to calling people by their names now.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Rated G", "Nobody in the room is allowed to cuss.  Drink when you slip up.", " F#$&, Sh*t, A$$, D*ck!!!  We know that was brutal, enjoy using all these fun words again.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Beer B*tch", "You're responsible for everybody's refills.  Everybody take a drink to celebrate and be sure to thank {name} for their service!", "Congrats, you’re no longer the beer b*tch", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Question Master", "You are now the Question Master, {name}.  Anyone who answers your questions will drink.  Remind them of this every time you trick them into answering a question.", "You’re no longer the question master.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Thumbs Up", "At any time, when you put your thumb up, the last person to comply has to drink.", "Put your damn thumb down.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "The Jackass", "Answer everything with a question.  Only ask questions, no statements from you.  Drink every time you forget.", "Please stop answering everything with a f*cking question.", "{name} is no longer inconvenienced.");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "I'll Be Back", "Anyone at any point can point at you and 'remind' you that you need to do something.  At which point you must say \"I'll be back!\" and leave the room for 10 seconds.  Have a drink for the road.", "Everyone who made {name} leave the room have a drink.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Curling Time", "You will now curl into the fetal position and stay there until this inconvenience is vacated, and enjoy having your friends laugh at you while you still play from the ground.", "Get off the ground you idiot.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "What’s wrong with that guy?", "Every now and then you have to shout something random.  Get creative with it.  If somebody notices you've gone 3 turns without doing this, you drink.", "Everybody’s sick of the random sh*t coming out of your mouth.", "{name} is no longer inconvenienced.");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "This is Sparta", "The only words that you can speak are \"This is Sparta!\".  You also have to scream it.  If you don't there will be a punishment of spears (if somebody catches you slipping, you're downing that drink)", "We get it.  This is Sparta.  You can stop now.", "{name} is no longer inconvenienced.");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Do the Flamingo", "Stand on 1 leg.  Any time that other foot touches ground, you drink.", "How long have you been standing like that?  Put your other foot back down like a normal person.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Squirrel!!!", "Make a squirrel face, you know, stick your top teeth out.  Anytime you forget, you drink.", "What’s wrong with your face?  You look like a squirrel.  Cut that sh*t out.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Keep It Going", "Start Walking around the room.  Never stop moving.  Anytime you do, have a drink.", "Stop moving around and sit down.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Pffffffft", "You can only speak in fart noises.  Anything you say that isn't a squeaker, a trumpet, or a silent but deadly means a drink.", "Ok, you can stop talking in fart noises stinky.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Born to Runner Up", "Jog in place.  If your feet stop moving, your hands better lift that drink up and take a swallow.", "Enough with the running in place already.If you kept it going the whole time congrats.Hand out a 5 second chug to the room.", "{name} is no longer Inconvenienced");
        gameController.AddCardToDeck(CardsManager.inconvenienceCards, "Inconvenience", 1, "Unhearable", "The crowd chooses a word that you cannot hear.  Everytime someone says it, you must drink.", "Wow that hurt.  I bet everyone said the word that you can’t hear.  Sorry about that.", "{name} is no longer Inconvenienced");
    }
}